//PART 1: COMMENT BOX DECLARATION
//this.state is private to the component and can be changed by calling this.setState().
//When the state updates, the component re-renders itself.
//componentDidMount is a method called automatically by React after
//a component is rendered for the first time.
import React from "react";
import $ from "jquery";
import CommentForm from "./CommentForm";
import CommentList from "./CommentList";

var CommentBox = React.createClass({
    //function to GET comments from server
    loadCommentsFromServer: function() {
        $.ajax({
            url: this.props.url,
            dataType: 'json',
            cache: false,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },
    // Function to submit to the server and refresh the list
    handleCommentSubmit: function(comment) {
        // Make it faster
        var comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        var newComments = comments.concat([comment]);
        this.setState({data: newComments});

        $.ajax({
            url: this.props.url,
            dataType: 'json',
            type: 'POST',
            data: comment,
            success: function(data) {
                this.setState({data: data});
            }.bind(this),
            error: function(xhr, status, err) {
                this.setState({data: comments});
                console.error(this.props.url, status, err.toString());
            }.bind(this)
        });
    },
    //this executes only once during the "lifecycle"
    getInitialState: function() {
        return {
            data: []
        };
    },
    componentDidMount: function() {
        this.loadCommentsFromServer();
        setInterval(this.loadCommentsFromServer, this.props.pollInterval);
    },
    render: function() {
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList data={this.state.data} />
                <CommentForm onCommentSubmit={this.handleCommentSubmit} />
            </div>
        );
    }
});

export default CommentBox;